// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sampler_randint
Rcpp::List sampler_randint(arma::mat YY, arma::mat XX, arma::mat ZZ, arma::mat XXl, arma::mat XXT, arma::vec dj, int Niter, int burn, int thin, arma::vec hyper_theta_x, arma::vec hyper_theta_z, arma::vec penmig_lin, arma::vec penmig_nl, arma::vec tx, arma::vec tz, arma::vec prior_int, bool upsv, int hereditariety, bool conlnl, arma::vec grplabel, int ngroup, arma::vec theta_init, arma::vec theta_init2);
RcppExport SEXP _ssdmreg_sampler_randint(SEXP YYSEXP, SEXP XXSEXP, SEXP ZZSEXP, SEXP XXlSEXP, SEXP XXTSEXP, SEXP djSEXP, SEXP NiterSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP hyper_theta_xSEXP, SEXP hyper_theta_zSEXP, SEXP penmig_linSEXP, SEXP penmig_nlSEXP, SEXP txSEXP, SEXP tzSEXP, SEXP prior_intSEXP, SEXP upsvSEXP, SEXP hereditarietySEXP, SEXP conlnlSEXP, SEXP grplabelSEXP, SEXP ngroupSEXP, SEXP theta_initSEXP, SEXP theta_init2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type YY(YYSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XXl(XXlSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XXT(XXTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dj(djSEXP);
    Rcpp::traits::input_parameter< int >::type Niter(NiterSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_theta_x(hyper_theta_xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_theta_z(hyper_theta_zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type penmig_lin(penmig_linSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type penmig_nl(penmig_nlSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tx(txSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tz(tzSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_int(prior_intSEXP);
    Rcpp::traits::input_parameter< bool >::type upsv(upsvSEXP);
    Rcpp::traits::input_parameter< int >::type hereditariety(hereditarietySEXP);
    Rcpp::traits::input_parameter< bool >::type conlnl(conlnlSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type grplabel(grplabelSEXP);
    Rcpp::traits::input_parameter< int >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_init2(theta_init2SEXP);
    rcpp_result_gen = Rcpp::wrap(sampler_randint(YY, XX, ZZ, XXl, XXT, dj, Niter, burn, thin, hyper_theta_x, hyper_theta_z, penmig_lin, penmig_nl, tx, tz, prior_int, upsv, hereditariety, conlnl, grplabel, ngroup, theta_init, theta_init2));
    return rcpp_result_gen;
END_RCPP
}
// sampler
Rcpp::List sampler(arma::mat YY, arma::mat XX, arma::mat ZZ, arma::mat XXl, arma::mat XXT, arma::vec dj, int Niter, int burn, int thin, arma::vec hyper_theta_x, arma::vec hyper_theta_z, arma::vec penmig_lin, arma::vec penmig_nl, arma::vec tx, arma::vec tz, arma::vec prior_int, bool upsv, int hereditariety, bool conlnl, arma::vec theta_init, arma::vec theta_init2);
RcppExport SEXP _ssdmreg_sampler(SEXP YYSEXP, SEXP XXSEXP, SEXP ZZSEXP, SEXP XXlSEXP, SEXP XXTSEXP, SEXP djSEXP, SEXP NiterSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP hyper_theta_xSEXP, SEXP hyper_theta_zSEXP, SEXP penmig_linSEXP, SEXP penmig_nlSEXP, SEXP txSEXP, SEXP tzSEXP, SEXP prior_intSEXP, SEXP upsvSEXP, SEXP hereditarietySEXP, SEXP conlnlSEXP, SEXP theta_initSEXP, SEXP theta_init2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type YY(YYSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XXl(XXlSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XXT(XXTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dj(djSEXP);
    Rcpp::traits::input_parameter< int >::type Niter(NiterSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_theta_x(hyper_theta_xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_theta_z(hyper_theta_zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type penmig_lin(penmig_linSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type penmig_nl(penmig_nlSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tx(txSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tz(tzSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_int(prior_intSEXP);
    Rcpp::traits::input_parameter< bool >::type upsv(upsvSEXP);
    Rcpp::traits::input_parameter< int >::type hereditariety(hereditarietySEXP);
    Rcpp::traits::input_parameter< bool >::type conlnl(conlnlSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_init2(theta_init2SEXP);
    rcpp_result_gen = Rcpp::wrap(sampler(YY, XX, ZZ, XXl, XXT, dj, Niter, burn, thin, hyper_theta_x, hyper_theta_z, penmig_lin, penmig_nl, tx, tz, prior_int, upsv, hereditariety, conlnl, theta_init, theta_init2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ssdmreg_sampler_randint", (DL_FUNC) &_ssdmreg_sampler_randint, 23},
    {"_ssdmreg_sampler", (DL_FUNC) &_ssdmreg_sampler, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_ssdmreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
