# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampler_randint <- function(YY, XX, ZZ, XXl, XXT, dj, Niter, burn, thin, hyper_theta_x, hyper_theta_z, penmig_lin, penmig_nl, tx, tz, prior_int, upsv, hereditariety, conlnl, grplabel, ngroup, theta_init, theta_init2) {
    .Call('_ssdmreg_sampler_randint', PACKAGE = 'ssdmreg', YY, XX, ZZ, XXl, XXT, dj, Niter, burn, thin, hyper_theta_x, hyper_theta_z, penmig_lin, penmig_nl, tx, tz, prior_int, upsv, hereditariety, conlnl, grplabel, ngroup, theta_init, theta_init2)
}

sampler <- function(YY, XX, ZZ, XXl, XXT, dj, Niter, burn, thin, hyper_theta_x, hyper_theta_z, penmig_lin, penmig_nl, tx, tz, prior_int, upsv, hereditariety, conlnl, theta_init, theta_init2) {
    .Call('_ssdmreg_sampler', PACKAGE = 'ssdmreg', YY, XX, ZZ, XXl, XXT, dj, Niter, burn, thin, hyper_theta_x, hyper_theta_z, penmig_lin, penmig_nl, tx, tz, prior_int, upsv, hereditariety, conlnl, theta_init, theta_init2)
}

